### ISSUE TITLE
Byte arrays becoming byte array arrays in VB.

### ISSUE THREAD

**Issue by LightningDragon** [0xd4d/dnSpy#122]
For some reason when a byte array gets turned into VB, It becomes a byte array array. happens with local variables as well not just class members.

`public static readonly byte[] SvCipher = new byte[] {42, 68, 76, 101};`

becomes.

`Public SvCipher As Byte() = New Byte()() { 42, 68, 76, 101 }`

**Comment by 0xd4d** [comment]
I think this has been fixed in the latest ILSpy decompiler source code.

**Comment by LightningDragon** [comment]
I just built the latest version of ILSpy and it does seem to be fixed. The `Using Dim` issue is still there though, so I'll leave that issue open.
